version: '3'
services:
  mysql:
    image: mysql
    restart: always
    ports:
    - 3306:3306
    - 33060:33060
    secrets:
    - DB_PASSWORD
    - DB_NAME
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=${DB_NAME}
  hr-server:
    image: rusenburn/hr-server:latest
    ports: 
    - 80:80
    secrets:
    - DB_PASSWORD
    - DB_NAME
    environment:
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - DB_SERVER=${DB_SERVER}
    depends_on:
    - mysql

  hr-client:
    image: rusenburn/hr-client:latest
    ports:
    - 8080:80
    depends_on:
    - hr-server