version: "3"
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db-vol:/var/lib/mysql

  hr-server:
    image: rusenburn/hr-server:latest
    ports:
      - 80:80
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SERVER=${DB_SERVER}
    depends_on:
      - mysql

  hr-client:
    image: rusenburn/hr-client:latest
    ports:
      - 8080:80
    depends_on:
      - hr-server
volumes: 
  db-vol:
    driver: local
