"""Adding Employees and Job Hisory Tables

Revision ID: 6392989f5dbc
Revises: 47de8a4a8697
Create Date: 2022-04-11 16:22:05.676827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6392989f5dbc'
down_revision = '47de8a4a8697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=52), nullable=False),
    sa.Column('last_name', sa.String(length=52), nullable=False),
    sa.Column('email', sa.String(length=52), nullable=False),
    sa.Column('phone_number', sa.String(length=52), nullable=False),
    sa.Column('hire_date', sa.DateTime(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employees_job_id'), 'employees', ['job_id'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_table('job_histories',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('employee_id', 'start_date')
    )
    op.create_index(op.f('ix_job_histories_employee_id'), 'job_histories', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_histories_employee_id'), table_name='job_histories')
    op.drop_table('job_histories')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_job_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
