"""creating_regions_and_countries_tables

Revision ID: 17be3d4cef95
Revises: 
Create Date: 2022-04-08 04:06:19.631346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17be3d4cef95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('region_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_index(op.f('ix_regions_region_id'), 'regions', ['region_id'], unique=False)
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=64), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('country_name')
    )
    op.create_index(op.f('ix_countries_country_id'), 'countries', ['country_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_country_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_regions_region_id'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
